### ISSUE TITLE
How do i build it on ubuntu

### ISSUE THREAD

**Issue by gitdrug** [tareksander/termux-gui#1]
Queston
How do i build this app do i just install koltin and then open build.graddle in the terminal?

**Comment by gitdrug** [comment]
Nevermind i figured out how to compile it but running gradlew

**Comment by gitdrug** [comment]
nevermind it dosent provide a apk if i run gradlew im kinda dumb

**Comment by gitdrug** [comment]
ill just wait to use it untill a fdroid build comes out

**Comment by tareksander** [comment]
The easiest way is to [download Android Studio](https://developer.android.com/studio).  

Then after opening Android Studio click on File on the top left -> New -> Project from Version Control. Then enter the git repository URL. After the project is imported you can click the green hammer icon to build it. The apk will be placed in build/output/apk/debug.

Then you have to do the same for Termux. Building Termux also requires the NDK, so you need a few GB of storage.  

To use the apk you have to backup Termux, uninstall it (and all plugins) and use the apks you build to install it again.

**Comment by tareksander** [comment]
I now attached an apk to the release, it should be compatible with the [Termux Github Actions builds](https://github.com/termux/termux-app/actions).
